Serve:
  mode: release
  port: :8080
Logger:
  # in the same directory.  It uses <processname>-lumberjack.log in
  # os.TempDir() if empty.
  # example: /var/log/test.log
  filename: E:\\github.com\\hxx258456\\pyramidel-chain-baas\\log\\serve.log
  # MaxSize is the maximum size in megabytes of the log file before it gets
  # rotated. It defaults to 100 megabytes.
  maxsize: 50
  # 旧日志文件保存的最大天数,天为单位
  maxage: 25
  # 保留的旧日志文件最大数量
  maxbackups: 35
  # 是否压缩日志文件,目前只支持gzip压缩
  compress: true
  # 默认使用utc时间戳,为true则使用本地时间
  localtime: true
  # 日志级别全部小写或全部大写
  # 日志级别参照uber-zap
  level: info
  # 日志中间件忽略的gin路由
  skippaths:
    - /test