Port:
  8080
Logger:
  # in the same directory.  It uses <processname>-lumberjack.log in
  # os.TempDir() if empty.
  # example: /var/log/test.log
  filename: test.log
  # MaxSize is the maximum size in megabytes of the log file before it gets
  # rotated. It defaults to 100 megabytes.
  maxsize: 50
  # 旧日志文件保存的最大天数,天为单位
  maxage: 25
  # 保留的旧日志文件最大数量
  maxbackups: 35
  # 是否压缩日志文件,目前只支持gzip压缩
  compress: true
  # 默认使用utc时间戳,为true则使用本地时间
  localtime: true
MySql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "mysql"
  dbname: "blue_bell"
  max_open_conns: 200
  max_idle_conns: 50
Redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100